#!/bin/sh -e

export DESTDIR="$1"

# Remove po/ dir, and usless i18n module.
sed -e "/subdir('po')/d" -e "/i18n/d" meson.build > _
mv -f _ meson.build

meson setup \
    -Dprefix=/usr \
    -Dcompat-rules=true \
    -Dxorg-rules-symlinks=true \
    -Dxkb-base="/usr/share/X11/xkb" \
    output

ninja -C output
ninja -C output install
